"""add monument field configs

Revision ID: cf765548a67f
Revises: 72b8f93a2bfd
Create Date: 2026-06-01 17:51:01.961004

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf765548a67f'
down_revision: Union[str, Sequence[str], None] = '72b8f93a2bfd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('route_stops', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('route_stops', 'updated_at')
    # ### end Alembic commands ###
