"""add city id to monuments

Revision ID: 7c2ef20f5d95
Revises: cf765548a67f
Create Date: 2026-06-02 19:45:16.725881

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "7c2ef20f5d95"
down_revision: Union[str, Sequence[str], None] = "cf765548a67f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "monuments",
        sa.Column("city_id", sa.String(), nullable=False, server_default="unknown"),
    )
    op.create_index(
        op.f("ix_monuments_city_id"), "monuments", ["city_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_monuments_city_id"), table_name="monuments")
    op.drop_column("monuments", "city_id")
    # ### end Alembic commands ###
